#+AUTHOR: Andrew Lyjak
#+EMAIL: andrew.lyjak@gmail.com
#+OPTIONS: todo:nil
#+OPTIONS: toc:nil
#+OPTIONS: tags:nil
#+OPTIONS: prop:Effort
#+OPTIONS: ^:{}
#+STARTUP: indent
#+COLUMNS: %TODO %PRIORITY(P) %70ITEM(Task) %TAGS %8Effort(Estimated Effort){:} %DEADLINE
#+TAGS: h3d alyjak sow_1 sow_2 upkeep invoice1 invoice2
#+PROPERTY: Effort_ALL 0 1:00 2:00 4:00 8:00 16:00 24:00 40:00 80:00


* TODO H3D SOW #4                                                 :h3d:sow_4:
The tasks and services agreed upon by the parties listed within the Consulting Agreement are
described herein. Work is divided into payment milestones, who's description and price is described
within the [[SOW4_milestones][following table]]. Payment is expected upon completion of each milestone. The total
contract value, consisting of the sum of each milestone, is listed as the first line item of the
table. After notification by the consultant, *A Lyjak Cybernetics Consulting LLC*, the Client's
technical authority for the contract, *Jason Jaworski*, is responsible for affirming that all
sub-tasks enumerated within a milestone are confirmed satisfactorily complete. Evaluation is
expected within *10* business days of receiving notice of milestone completion. Payment is expected
within *one month* of an affirmative evaluation. It is the consultant's responsibility to respond
and incorporate feedback based on the technical authority's review before re-notifying the client of
milestone completion.

#+NAME:SOW4_milestones
#+BEGIN: columnview :format "%ITEM(Task) %Effort(Effort in HH:MM){:} %Price(Price in $)" :hlines 2 :maxlevel 3
#+CAPTION: Estimated effort (HH:MM) for each task, total effort and price for the SOW
#+TBLFM: $3=$2*120;tE
| Task                                                      | Effort in HH:MM | Price in $ |
|-----------------------------------------------------------+-----------------+------------|
| Integrate Warranty Data (rollover from SOW#3)             |           24:00 |            |
|-----------------------------------------------------------+-----------------+------------|
| Upgrade production server                                 |           24:00 |            |
|-----------------------------------------------------------+-----------------+------------|
| Integrate IpV6 Multicast local network detector discovery |            8:00 |            |
|-----------------------------------------------------------+-----------------+------------|
| Create Subassembly UI for multi-headed detectors          |           24:00 |            |
|-----------------------------------------------------------+-----------------+------------|
| Model/Config Code UI Fix                                  |            2:00 |            |
|-----------------------------------------------------------+-----------------+------------|
| Create a Test Burn setting                                |            4:00 |            |
|-----------------------------------------------------------+-----------------+------------|
| Create a Statement of Work for Fishbowl integration       |           24:00 |            |
|-----------------------------------------------------------+-----------------+------------|
| **Total H3D SOW #4**                                      |          110:00 | $13,200    |
|-----------------------------------------------------------+-----------------+------------|
#+END:
#+TBLFM: $3=$2*120;tE


** TODO Integrate Warranty Data (rollover from SOW#3)
  :PROPERTIES:
  :EFFORT:   24:00
  :END:

Warranty end date will inform what the newest update patch the customer is entitled to as a
suggestion for patch to apply. The source of truth for this warranty data is on Sharepoint.

- [ ] Create a script that authorized users can use to download the warranty data from Sharepoint,
  and integrate it into the H3ID database.
- [ ] Create a warning for authorized users notifying them if it's been over a week since the
  warranty data was synchronized, and pointing them to the instructions on how to perform the
  operation
- [ ] Customize what patch(es) are available per detector based on the linked warranty information
  and whether the patch is classified as a security update.

** TODO Upgrade production server
  :PROPERTIES:
  :EFFORT:   24:00
  :END:

- [ ] Test All SOW2, SOW3, and SOW4 features in the presence of an H3ID representative
- [ ] Upgrade system dependencies in order to ensure security fixes are in place in the code and the
  virtual server
- [ ] Perform practice migration on the test server
- [ ] Perform production migration outside of normal business hours

** TODO Integrate IpV6 Multicast local network detector discovery
  :PROPERTIES:
  :EFFORT:   8:00
  :END:

If the new firewall supports IpV6 multicast, enable the multicast detector discovery scripts and
test their functionality.

** TODO Create Subassembly UI for multi-headed detectors
  :PROPERTIES:
  :EFFORT:   24:00
  :END:

Enable programming/configuration of multi-headed detectors both as individual heads as well as the
full assembly. Create a UI for joining heads into a multi-headed detector and batch configuring them.

- [ ] Create a prototype design with feedback from Jason and other stakeholders
- [ ] Implement final design
- [ ] Test all designed features

** TODO Model/Config Code UI Fix
  :PROPERTIES:
  :EFFORT:   2:00
  :END:

If the model/config code are not set for a given unit, don't show the default code/config. Leave it
blank so it is obvious it is not set.

** TODO Create a Test Burn setting
  :PROPERTIES:
  :EFFORT:   4:00
  :END:

Add a way to burn a SOM for a test and not have the burn record show up in the history/logs of a
production unit.

** Create a Statement of Work for Fishbowl integration
  :PROPERTIES:
  :EFFORT:   24:00
  :END:

Work with stakeholders to create process and workflow diagrams to understand how H3ID should
optimally integrate with FishBowl. After design consultation and design review of the vision, create
a statement of work for the necessary implementation and testing to achieve the agreed upon design.
